# Generated by Django 4.0.2 on 2022-04-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_address1_alter_order_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
    ]
