# Generated by Django 4.0.2 on 2022-04-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
