# Generated by Django 4.0.2 on 2022-04-24 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
