# Generated by Django 4.0.2 on 2022-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles')], default='NaN', max_length=5),
        ),
        migrations.AddField(
            model_name='product2',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles')], default='NaN', max_length=5),
        ),
    ]
