# Generated by Django 4.0.2 on 2022-08-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('G', 'Grocery'), ('E', 'Electronics'), ('C', 'Clothes'), ('BS', 'Basic Stuffs'), ('A', 'Appliances'), ('G', 'Grocery'), ('T', 'Toys')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product2',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('G', 'Grocery'), ('E', 'Electronics'), ('C', 'Clothes'), ('BS', 'Basic Stuffs'), ('A', 'Appliances'), ('G', 'Grocery'), ('T', 'Toys')], max_length=2),
        ),
    ]
