# Generated by Django 4.0.2 on 2022-08-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_category_alter_product2_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
